version: '3.8'

services:
  web:
    container_name: weld_prediction
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    ports:
      - '127.0.0.1:5043:5000'